// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: tspi_ui

#include "ui.h"

void btn_test(lv_event_t * e)
{
	// Your code here
}
